stages:
  - lint
  - test
  - build
  - scanning

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

lint:
  stage: lint
  image: node:20-alpine
  script:
    - npm install --force
    - npm run lint
  only:
    - main

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t mouadchaouni/pitstop:pitstop-vehicle-service .
    - docker push mouadchaouni/pitstop:pitstop-vehicle-service
  only:
    - main

container_scanning:
  stage: scanning
  variables:
    CS_IMAGE: mouadchaouni/pitstop:pitstop-vehicle-service
  needs:
    - build